### ISSUE TITLE
Support execute transactions from Trezor.

### ISSUE THREAD

**Issue by moisses89** [safe-global/safe-cli#326]
# What is needed?
Add support to send transactions from Trezor. 

# Background
Currently we can sign transactions with Trezor, but send transactions from Trezor is not supported. 

# Related issues
#325

**Comment by aspiers** [comment]
It seems that the following is needed:

- [ ] implement `get_signed_raw_transaction()` in `safe_cli/operators/hw_wallets/trezor_wallet.py`
- [ ] change `load_hw_wallet()` in `safe_cli/operators/safe_operator.py` so that `self.hw_wallet_manager.set_sender()` is called not just when `hw_wallet_type == HwWalletType.LEDGER` but also when `hw_wallet_type == HwWalletType.TREZOR`

Is there anything else?

**Comment by moisses89** [comment]
@aspiers you are right, it was implemented here #337

**Comment by JagoFigueroa** [comment]
Looks good to me, thanks!
